# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

                                                                                            
#                             &    @/       &.    @                             
#                            @       @@   @@                                    
#                            . @@@   @@ @ @.   @@*                              
#                             &   @@&@@@@@@@&@@   @                             
#                             .@@@%@@@@@@@@@@@@@@%                              
#                       %%     @@@ @@@@@@@@@@@@@       @*                       
#                     @         &@@@   @@@    @@@         @                     
#                     @         @  @@@ @@@    @@@         @                     
#                       @@     @   @@@@@@@@@@@@        @                        
#                              (@@@@@  @@@  @@@@@&                              
#                             & @@@   &@@@@   @@@ @                             
#                            . @@&     @@@     @@@                              
#                            @        @   %                                     
#                             &    @        @*    @                              


## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://sciencetokeepanion.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Science to Keep an Ion
tagline: Better not lose sight of this!!
logo: /apple-touch-icon.png
image: /android-chrome-512x512.png
description: > # this means to ignore newlines until "Language & timezone"
  Work in progress... test test test test test test testtest test test test test test test test test test test  v test test test test test test test test test.


## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: Asia/Kolkata # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## => Ownership Verification
##############################
webmaster_verifications:
  google: ##1234
  bing: ##1234
  alexa: ##1234
  yandex: ##1234
  baidu: ##1234


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Taran Raj K
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     : taranrajk2203@gmail.com
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : TaranRajK1 # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : TRKD02 # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => Feed Settings
#####################
feed:
  excerpt_only: true # excludes the content and includes only the excerpt in the RSS feed


##twitter:
##  card: summary_large_image


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: ScienceToKeepAnIon/ScienceToKeepAnIon.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : /archive/ # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: unpkg # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addtoany # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

    
## => Compress
################
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: true
    profile: false
    startings: []


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: google # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : G-W2C1F7W0EZ # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : pretty

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
  - /docker

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
      image: /android-chrome-512x512.png

kramdown:
  math_engine: katex

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - amp-jekyll